name: MuezliPlugin
main: me.ScottSpittle.MuezliPlugin.Main
authors: [ScottSpittle, Carhartjimmy]
version: 1.1.1
description: Muezli's First Plugin
commands:
  sendme:
    description: send mofo message...
  willieport:
    description: teleport like a boss.
  roll:
    description: roll the dice xD
  motd:
    description: roll the dice xD
