name: MuezliPlugin
main: me.ScottSpittle.MuezliPlugin.Main
authors: [ScottSpittle, Carhartjimmy]
version: 1.0
softdepend: [Vault]
description: Muezli's First Plugin
commands:
  muezli:
    description: command
