name: MuezliPlugin
main: me.ScottSpittle.MuezliPlugin.Main
authors: [ScottSpittle, Carhartjimmy]
version: 1.0
description: Muezli's First Plugin
commands:
  sendme:
    description: send mofo message...
  willieport:
    description: teleport like a boss.
